# Generated by Django 5.1.4 on 2025-01-20 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(max_length=3)),
                ('name_prefix', models.CharField(max_length=4)),
                ('email', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('passcode', models.CharField(max_length=6)),
                ('contact', models.CharField(max_length=11)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employeerole')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employeestatus')),
            ],
        ),
    ]
