# Generated by Django 5.1.4 on 2025-01-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='middle_initial',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name_prefix',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ManyToManyField(blank=True, to='api.employeerole'),
        ),
    ]
