# Generated by Django 5.1.5 on 2025-01-24 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
