# Generated by Django 5.1.5 on 2025-01-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
        migrations.AlterField(
            model_name='employee',
            name='passcode',
            field=models.CharField(max_length=128),
        ),
    ]
