from django.contrib import admin
from django.urls import path, include
from api import views
from api.views import *
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', views.home, name='test_jwt'),
    path('fetch-employee-data/', views.fetch_employee_data, name='fetch_employee_data'),
    path('fetch-attendance-data/', views.fetch_attendance_data, name='fetch_attendance_data'),
    path('time-in/', views.time_in, name='time_in'),
    path('time-out/', views.time_out, name='time_out'),
    path('fetch-items-page-data/', views.fetch_items_page_data, name='fetch_items_page_data'),
    path('fetch-inventory-page-data/', views.fetch_inventory_page_data, name='fetch_inventory_page_data'),
    path('fetch-stockin-page-data/', views.fetch_stockin_page_data, name='fetch_stockin_page_data'),
    path('fetch-stockout-page-data/', views.fetch_stockout_page_data, name='fetch_stockout_page_data'),
    path('fetch-menu-data/', views.fetch_menu_data, name='fetch_menu_data'),
    path('fetch-item-data/', views.fetch_item_data, name='fetch_item_data'),
    path('add-inventory/', views.add_inventory, name='add-inventory'),
    path('add-item/', views.add_item, name='add_item'),
    path('edit-item/<int:item_id>/', views.edit_item, name='edit_item'),
    path('delete-item/<int:item_id>/', views.delete_item, name='delete_item'),
    path('add-category/', views.add_category, name='add_category'),
    path('edit-category/<int:category_id>/', views.edit_category, name='edit_category'),
    path('delete-category/<int:category_id>/', views.delete_category, name='delete_category'),
    path('add-supplier/', views.add_supplier, name='add_supplier'),
    path('edit-supplier/<int:supplier_id>/', views.edit_supplier, name='edit_supplier'),
    path('delete-supplier/<int:supplier_id>/', views.delete_supplier, name='delete_supplier'),
    path('add-stockin-data/', views.add_stockin_data, name='add_stockin_data'),
    path('edit-receipt-stockin-data/<int:receipt_id>/', views.edit_receipt_stockin_data, name='edit_receipt_stockin_data'),
    path('delete-receipt/<int:receipt_id>/', views.delete_receipt, name='delete_receipt'),
    path('dispose-item/', views.dispose_item, name='dispose_item'),
    path('add-menu/', views.add_menu_item, name='add_menu_item'),
    path('edit-menu/<int:menu_id>/', views.edit_menu_item, name='edit_menu_item'),
    path('delete-menu/<int:menu_id>/', views.delete_menu_item, name='delete_menu_item'),
    path('add-menu-category/', views.add_menu_category, name='add_menu_category'),
    path('edit-menu-category/<int:category_id>/', views.edit_menu_category, name='edit_menu_category'),
    path('delete-menu-category/<int:category_id>/', views.delete_menu_category, name='delete_menu_category'),
    path('fetch-order-data/', views.fetch_order_data, name='fetch_order_data'),
    path('fetch-order-data/<int:transactionId>/', views.fetch_order_data, name='fetch_transaction_data'),
    path('add-discount/', views.add_discount, name='add_discount'),
    path('edit-discount/<int:discount_id>/', views.edit_discount, name='edit_discount'),
    path('delete-discount/<int:discount_id>/', views.delete_discount, name='delete_discount'),
    path('edit-delivery-deduction/<int:delivery_id>/', views.edit_delivery_deduction, name='edit_delivery_deduction'),
    path('edit-unli-wings-base-amount/<int:category_id>/', views.edit_unli_wings_base_amount, name='edit-unli-wings-base-amount'),
    path('add-order/', views.add_order, name='add_order'),
    path('edit-order/<int:transaction_id>/', views.edit_order, name='edit_order'),
    path('update-order-status/<int:transaction_id>/', views.update_order_status, name='update_order_status'),
    path('update-menu-availability/', views.update_menu_availability, name='update_menu_availability'),
    path('check-menu-inventory/<int:menu_id>', views.check_menu_inventory, name='check_menu_inventory'),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/login/', views.login_view, name='login'),
    path('api/test/', views.test_connection, name='test_connection'),
    path("api/add-employee/", views.add_employee, name="add_employee"),
    path("api/delete-employee/<int:employee_id>/", views.delete_employee, name="delete_employee"),
    path("api/edit-employee/<int:employee_id>/", views.edit_employee, name="edit_employee"),
]
